### ISSUE TITLE
No support for the latest Minestom version

### ISSUE THREAD

**Issue by JasperTheMinecraftDev** [TogAr2/MinestomPvP#29]
Hey, I tried to use this on my Minestom CE server and it sadly failed to work. The Extension class isn't present in the latest Minestom versions anymore. Can you look at that?

**Comment by JasperTheMinecraftDev** [comment]
I've created a fork of this project which removes removes the Extension class which effectively renders it unusable as a extension but it works fine as a library. The fork can be found in my repositories if anyone needs it. Hopefully a official solution will be provided soon!

**Comment by JasperTheMinecraftDev** [comment]
I've also fixed the sound errors in my fork. Is this still maintained? Otherwise I can maybe take it over.

**Comment by UserJHansen** [comment]
> The fork can be found in my repositories if anyone needs it. 

Hi Jasper, is it possible to get a copy of this fork, I can't seem to find it on your repo list.

**Comment by TogAr2** [comment]
Hey Jasper!

I finally decided to get back into this project. It is now completely updated to the latest Minestom version (along with several improvements to projectiles). I haven't done rigorous testing yet but everything seems to be working.

I looked at your fork and it seems to me that some solutions are a little hacky. I think its best to not integrate those in the original repository. You are however very welcome to contribute to this repository! I think it's great you're willing to help improving the library.

Could you maybe give me a list of all the things that you fixed in your version, so I can take a look at it? Of course you can also just open a pull request if you want. Also, what exactly are the sound errors you are talking about?
